name: DansProtocol
options:
  bundleIdPrefix: com.dansprotocol
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1"

targets:
  DansProtocol:
    type: application
    platform: iOS
    sources:
      - path: DansProtocol
        excludes:
          - "**/*.xcassets"
          - "**/Fonts/**"
          - "Info.plist"
          - "Resources/Questions.json"
      - path: DansProtocol/Resources/Questions.json
        type: file
        buildPhase: resources
      - path: DansProtocol/Resources/Fonts/PlayfairDisplay-VariableFont_wght.ttf
        type: file
        buildPhase: resources
      - path: DansProtocol/Resources/Fonts/NotoSerifKR-VariableFont_wght.ttf
        type: file
        buildPhase: resources
      - path: DansProtocol/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: DansProtocol/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.dansprotocol.DansProtocol
        PRODUCT_NAME: "Dan's Protocol"
        PRODUCT_MODULE_NAME: DansProtocol
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: DansProtocol/DansProtocol.entitlements
      properties:
        com.apple.security.app-sandbox: true

  DansProtocolTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DansProtocolTests
    dependencies:
      - target: DansProtocol
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Dan's Protocol.app/Dan's Protocol"
        PRODUCT_BUNDLE_IDENTIFIER: com.dansprotocol.DansProtocolTests
        GENERATE_INFOPLIST_FILE: YES

  DansProtocolUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: DansProtocolUITests
    dependencies:
      - target: DansProtocol
    settings:
      base:
        TEST_TARGET_NAME: DansProtocol
        PRODUCT_BUNDLE_IDENTIFIER: com.dansprotocol.DansProtocolUITests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  DansProtocol:
    build:
      targets:
        DansProtocol: all
        DansProtocolTests: [test]
        DansProtocolUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - DansProtocolTests
        - DansProtocolUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
